encyclopedia/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>",views.entry_page, name="title"),
    path("search/",views.search, name="search"),
    path("new_page/",views.new_page, name="new_page"),
    path("edit/", views.edit, name="edit"),
    path("save_edit/", views.save_edit, name="save_edit"),
    path("rand/", views.random_page, name="random_page")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from . import util
from django import forms
import markdown
import random

class NewContentForm(forms.Form):
    title = forms.CharField(label="Title",widget=forms.TextInput())
    content = forms.CharField(label="Content",widget=forms.Textarea(attrs={'style': 'height: 60vh;'}))

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def convert_markdown(title):
    content = util.get_entry(title)
    markdowner = markdown.Markdown()
    if content is None:
        return None
    else:
        return markdowner.convert(content)


def entry_page(request, title):

    page = convert_markdown(title)
    
    if page is None:
        return render(request,"encyclopedia/error.html", {
            'error': "Page has not found"
        })
        
    else:
        return render(request,"encyclopedia/entry.html",{
        'title': title, 
        'content': page
    })
        
def search(request):
    if request.method == "POST":
        value = request.POST['q']
        content = convert_markdown(value)
        if content is None:
            # show the possible results
            entries = util.list_entries()
            valid_entries = []
            for entry in entries:
                if value.lower() in entry.lower():
                    valid_entries.append(entry)
            
            if len(valid_entries) == 0:
                return render(request,"encyclopedia/error.html", 
                {"error": "Page has not found"
                })
            else:
                return render(request,"encyclopedia/search.html",{
                    "entries":valid_entries,
                    "search":value
                })
        else:
            return render(request,"encyclopedia/entry.html",{
            'title': value, 
            'content': content
        })

def new_page(request):
    if request.method== "GET":
        return render(request,"encyclopedia/new.html",{
            "form": NewContentForm()
        })
    else:
        form = NewContentForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            check_title = util.get_entry(title)
            if check_title is not None:
                return render(request, "encyclopedia/error.html",{
                    "error": "The title already exist"
                })
            else: 
                util.save_entry(title,content)
                return render(request, "encyclopedia/entry.html",{
                    "title": title,
                    "content": convert_markdown(title)
                })
                # create new page 
        else:
            return render(request, "encyclopedia/new.html", {
                "form": form
            })

def edit(request):
    if request.method == 'POST':
        title = request.POST['entry_title']
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "content": content
        })

def save_edit(request):
    if request.method == "POST":
        title = request.POST['title']
        content = request.POST['content']
        util.save_entry(title,content)
        converted_content = convert_markdown(title)
        return render(request,"encyclopedia/entry.html",{
            "title":title,
            "content":converted_content
        })

def random_page(request):
    all_entries = util.list_entries()
    random_title = random.choice(all_entries)
    content = convert_markdown(random_title)
    return render(request,"encyclopedia/entry.html", {
        "title":random_title,
        "content":content
    }) 

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    EDIT
{% endblock %}

{% block body %}
    <h4>Edit the page</h4>
    <form action="{% url 'wiki:save_edit' %}" method="POST">
        {% csrf_token %}
        <label>Title:</label>
        <input type="text" name= "title" placeholder="Enter a title" value="{{ title }}">
        <br/><lable>Content:</lable> <br/>
        <textarea name = "content">{{content}}</textarea>
        <br/>
        <input type="submit" value="Edit">
    </form>
    
{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}

    {{title}}

{% endblock %}

{% block body %}

    {{ content | safe }}

    <form action="{% url 'wiki:edit' %}" method="POST">
        {% csrf_token %}
        <input type="hidden" name="entry_title" value="{{ title }}">  
        <input type="submit" value="edit">
    </form>
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}
{% block title%}
    Error
{% endblock %}

{% block body %}
    <h1> Error!</h1>
    {{error}}
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>
    
    <ul>
        {% for entry in entries %}
            <li><a href= "{% url 'wiki:title' title=entry %}">{{ entry }}</a> </li> 
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method ="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new_page' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random_page' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h4>Add New Content</h4>
    <form action="{% url 'wiki:new_page' %}" method="POST">
        {% csrf_token %}
        {{form | linebreaks}}
        <input type="submit" value="Save">
    </form>
    
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h5>Search</h5>
    <p>Search results for "{{search}}"</p>
    <ul>
        {% for entry in entries %}
            <li><a href= "{% url 'wiki:title' title=entry %}">{{ entry }}</a> </li> 
        {% endfor %}
    </ul>

{% endblock %}